### ISSUE TITLE
Types de plats

### ISSUE THREAD

**Issue by ld-web** [valmnt/Restolink#1]
Est-ce qu'un plat peut avoir plusieurs types ?
Pouvez-vous donner des exemples de types de plats ?

**Comment by Riukotashi** [comment]
Non un plat ne peut pas avoir plusieurs type.
Salade, burger, boisson, accompagnement, dessert ...

**Comment by ld-web** [comment]
Ok, donc c'est pour ça qu'on a la clé étrangère de type, dans le plat. Nickel
