### ISSUE TITLE
Restaurant / Restaurateur

### ISSUE THREAD

**Issue by ld-web** [valmnt/Restolink#3]
Est-ce qu'un restaurant peut être administré par plusieurs utilisateurs ?
Ou bien est-ce qu'un utilisateur uniquement peut administrer un restaurant ?

En-dehors des administrateurs de l'application évidemment.

**Comment by Riukotashi** [comment]
Un restaurant ne peut être administré que par un seul utilisateur.

**Comment by ld-web** [comment]
Ok ! Par contre j'ai du mal à voir le processus que vous voulez implémenter quand vous dites qu'un membre est d'abord un client et qu'il devient ensuite restaurateur.
Ca veut dire que tous les clients pourront créer des restaurants du coup ?
Si je suis restaurateur et que j'ai plusieurs restaurants, je pourrai en créer plusieurs ?

**Comment by Riukotashi** [comment]
Oui, tous les clients peuvent créer des restaurants.
Un restaurateur peut créer plusieurs restaurants.

**Comment by ld-web** [comment]
Dans ce cas, il faut peut-être prévoir un système de modération/validation par les administrateurs. Qu'en pensez-vous ?
Sinon ça peut vite devenir la foire aux restaurants dans l'application...

**Comment by Riukotashi** [comment]
Oui en effet il faudrait prévoir un système de validation.
Nous allons rajouter un booléen is_valid permettant de savoir si un restaurant est actif ou non.
Si la valeur est null => le restaurant est en attente et doit être validé ou refusé.
Si la valeur est à 1 => le restaurant a été validé par un admin.
Si la valeur est à 2 => le restaurant a été refusé par un admin.

**Comment by ld-web** [comment]
Un booléen peut uniquement prendre les valeurs "true" ou "false" (0 ou 1 en BDD), ça me paraît compliqué de le passer à 2.
Ce qu'il faudrait plutôt envisager, c'est un état **par défaut** pour le champ `is_active` (false par exemple), avec la possibilité pour un admin de modifier ce champ.
Est-ce que ça vous paraît clair ?

**Comment by Riukotashi** [comment]
Je me suis trompé, j'ai mis 2 au lieu de 0
Si la valeur est null => le restaurant est en attente et doit être validé ou refusé.
Si la valeur est à 1 => le restaurant a été validé par un admin.
Si la valeur est à 0 => le restaurant a été refusé par un admin.
Est-ce mieux?

**Comment by ld-web** [comment]
C'est mieux oui, mais je pense qu'avec une valeur par défaut ce serait plus simple...à vous de voir, postez ici votre choix d'implémentation

**Comment by Riukotashi** [comment]
En fait l'intérêt que la valeur de départ sois null est que l'on puisse différencier un restaurant refusé, d'un restaurant en attente de validation.
Nous allons donc partir sur ce choix d'implémentation.
Si la valeur est null => le restaurant est en attente et doit être validé ou refusé.
Si la valeur est à 1 => le restaurant a été validé par un admin.
Si la valeur est à 0 => le restaurant a été refusé par un admin.

**Comment by ld-web** [comment]
Ok nickel !
