### ISSUE TITLE
Reduc commande

### ISSUE THREAD

**Issue by ld-web** [valmnt/Restolink#4]
Pouvez-vous préciser le fonctionnement d'une réduction sur une commande dans l'application ?
En rapport au champ "reduc" dans la table "Commandes"

**Comment by Riukotashi** [comment]
Le champ reduc est une réduction, cela peut être appliqué a une commande. 
Le champ peut être null ou égal à la somme de la réduction (toujours positif). 
Cela fonctionnera sous forme de code promo.
Est-ce clair?

**Comment by ld-web** [comment]
Dans ce cas, le code promo correspond à quoi ?
Doit-il être associé à un pourcentage ? Un montant ? A-t-il une durée de validité ?
Ce n'est pas assez clair, il faudrait préciser ce qu'est un code promo.

**Comment by Riukotashi** [comment]
En ayant réfléchis, nous allons ajouter une nouvelle table "CodePromo", avec un id, le nom, le montant de réduction (en euros et toujours positif) et la date d'expiration.
Dans la commande, nous allons stocker l'id du code promo si il y a un code promo de renseigné.
Est-ce que cela vous semble plus cohérent et clair?

**Comment by ld-web** [comment]
Ca me paraît mieux oui, faites-moi une demande de review quand vous aurez mis le schéma à jour !
