### ISSUE TITLE
Liaison plat/restaurant

### ISSUE THREAD

**Issue by ld-web** [valmnt/Restolink#5]
Est-ce qu'un plat peut être réalisé par plusieurs restaurants ?
Dans le sens, peut-on envisager de consulter les restaurants qui font des salades lyonnaises, par exemple, dans l'application ?

C'est ok si vous n'avez pas prévu de le faire, c'est juste pour être sûr au niveau du choix de conception du modèle.

**Comment by Riukotashi** [comment]
Non ce n'est pas prévu dans l'application. 
Seulement des filtres sur les types de plats pourront être effectuer .

**Comment by ld-web** [comment]
Ok nickel !
